<?php require VIEWS_PATH . 'includes/header.phtml';?>
<div class="container">
    <?php require VIEWS_PATH . '/includes/messages.phtml';?>

    <div class="jumbotron">
        <h1>Loja Virtual</h1>
        <p>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Impedit, ullam cupiditate cum itaque molestias nostrum ducimus illo at velit ipsa libero possimus facilis sequi vel natus officia suscipit nulla accusamus!
        </p>
    </div>

    <div class="row">
       
    </div>

</div>
<?php require VIEWS_PATH . 'includes/footer.phtml';?>
